server:
  port: 2002

spring:
  application:
    name: seata-storage-service
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 19970409
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

#配置mybatis-plus及日志输出
mybatis-plus:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# seata 配置
seata:
  enabled: true
  # 分布式事务分组
  tx-service-group: txl_tx_group
  # seata配置中心
  config:
    type: nacos
    nacos:
      namespace: 703f23c3-d2ae-40b2-8c36-56872ce66bcd
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: Nacos
      password: Nacos
  # seata的注册中心
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 703f23c3-d2ae-40b2-8c36-56872ce66bcd
      cluster: default
      username: Nacos
      password: Nacos
  service:
    vgroup-mapping:
      txl_tx_group: default    #这里要特别注意和nacos中配置的要保持一直
  application-id: order-id
  # 默认开启数据源代理
  enable-auto-data-source-proxy: true
  # 代理模式默认AT
  data-source-proxy-mode: AT

