server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002 #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server
    fetch-registry: false #表示是否从Eureka Server获取注册的服务信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/