server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server
    fetch-registry: false #表示是否从Eureka Server获取注册的服务信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    enable-self-preservation: false #关闭自我保护机制